app/backend/todo/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :tasks
  
  root 'welcome#index'
end

app/backend/todo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/backend/todo/app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/backend/todo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/backend/todo/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index 
    @tasks = Task.all
  end 

  def show 
    @task = Task.find(params[:id])
  end

  def new 
    @task = Task.new
  end

  def edit 
    @task = Task.find(params[:id])
  end
  
  def create
    @task = Task.new(task_params)
    
    if @task.save
      redirect_to @task
    else 
      render 'new'
    end
  end
  
  def update 
    @task = Task.find(params[:id])
     
    if @task.update(task_params)
      redirect_to @task 
    else 
      render 'edit' 
    end 
  end
  
  def destroy 
    @task = Task.find(params[:id])
    @task.destroy 
    
    redirect_to tasks_path
  end
 
  private
    def task_params
      params.require(:task).permit(:title, :deadline)
    end
end 


 

app/backend/todo/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/backend/todo/app/helpers/application_helper.rb
module ApplicationHelper
end

app/backend/todo/app/helpers/tasks_helper.rb
module TasksHelper
end

app/backend/todo/app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/backend/todo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/backend/todo/app/views/tasks/_form.html.erb
<%= form_with model: @task, local: true do |form| %>
 
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@task.errors.count, "error") %> prohibited
        this task from being saved:
      </h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :deadline %><br>
    <%= form.text_area :deadline %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/backend/todo/app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', tasks_path %>

app/backend/todo/app/views/tasks/index.html.erb
<h1>All of your tasks!</h1>

<%= link_to 'New task', new_task_path %>
 
<table>
  <tr>
    <th>Title</th>
    <th>Deadline</th>
    <th colspan="3"></th>
    <th></th>
  </tr>
 
  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.deadline %></td>
      <td><%= link_to 'Show', task_path(task) %></td>
      <td><%= link_to 'Edit', edit_task_path(task) %></td>
      <td><%= link_to 'Delete', task_path(task),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/backend/todo/app/views/tasks/new.html.erb
<h1>New Task</h1>


<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/backend/todo/app/views/tasks/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>
 
<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |

<%= link_to 'Back', tasks_path %>

app/backend/todo/app/views/welcome/index.html.erb
<h1>Welcome!</h1>
<%= link_to 'My Blog', controller: 'tasks' %>